### ISSUE TITLE
admin_externalpage class allows you to pass required capability

### ISSUE THREAD

**Issue by danmarsden** [unesco-iesalc/paygw_bank#11]
when definining an externalpage setting you can simply pass the required capability in the 4th param rather than having to wrap it here...

https://github.com/unesco-iesalc/paygw_bank/blob/main/settings.php#L39-L45

there are some good examples of this in the core admin/settings/appearance.php page.

not a blocker for approval.

**Comment by unesco-iesalc** [comment]
I  see this parameter is not available in admin_category. I think i prefer not showing an empty category in the menu.

**Comment by danmarsden** [comment]
From memory I thought it only shows a category when there are settings within that category? - but I could be wrong... in any case - feel free to just close this as won't fix. :-)
