### ISSUE TITLE
User file upload error

### ISSUE THREAD

**Issue by lagguerra** [unesco-iesalc/paygw_bank#12]
Hello,

Before anything else, thank you for making this plugin available.
I have been trying to use it, but I always get an error when a user tries to upload a file with proof of bank transfer.

I am running moodle version 4.0.2 and the plugin latest version 2022070701

Aditional information:
- User is able to upload file files from with default moodle file attachment component
- Plugin is enabled and configured to allow user uploads
- Plugin is enabled as an enrolment method and configured to allow enrolment on payment enrolments

Steps to reproduce the problem:
- User selects bank transfer as payment method to enroll in a course
- User clicks on the Start process button and concept, total cost, transfer code and file selection area is displayed
- User selects a file and clicks on Upload this file button, after which the filename appears in the filepicker filelist
- At this point, a record is available in Pending transfer payments, but there is no file attached
- From the user side, the user only has available the upload button, but when he clicks on it, the same page is reloaded, including the filename in the filepicker filelist
- If he clicks again on the upload button, since it is the only one available, an error is display saying "Cannot create file 1/paygw_bank/transfer/1/test.pdf
- At this point, there is a new button "Continue" available, but if the user clicks on it, another error is reveived, saying "A required parameter (component) was missing, and it is not possible to proceed.

I hope the explanation was clear and thanks in advance for your help.

Best regards

**Comment by unesco-iesalc** [comment]
Yes it's clear.  
Thanks for the issue.

**Comment by unesco-iesalc** [comment]
Hi. Just downloaded the new version that fix the issue.
Thanks.

**Comment by lagguerra** [comment]
Hi,
Thank you for the update, I just tested it, it is working great.

If you are interested, i translated the language file to Portuguese, and I can share it.

Not sure if it is usefull to you, but I added code to pay.php, line 197, to send an email to the support account, when a transfer file is uploaded:

`// Send file to support user
 $mailcontent = get_string('send_support_mail', 'paygw_bank', ['username' => fullname($USER), 'concept' => $description, 'file_url' => $url->__toString()]);
 email_to_user(core_user::get_support_user(), core_user::get_support_user(), get_string('transfer_process_concluded', 'paygw_bank'), $mailcontent);`

I also added the following to the language file:
`$string['transfer_process_concluded'] = 'Transfer process concluded';
$string['send_support_mail'] = 'The user {$a->username} concluded the transfer payment for "{$a->concept}". File available at {$a->file_url}';`

Thanks again

**Comment by unesco-iesalc** [comment]
Hello Luis. The translations of plugins must be added in this online tool. https://lang.moodle.org. I already added the spanish translations, but there aren't validated yet. You can send me the translations in a issue or add in the online tool for yourself
Send an email to a user seems interesting, but i think it's better add another setting with the email account. I think the person that validates the payments usually will be some of accounting or financial department. Probably there is convenient send another mail at start of process.
