### ISSUE TITLE
Moodle 4.0.4+ (Build: 20221007) not working

### ISSUE THREAD

**Issue by AbdullahAlSalim** [unesco-iesalc/paygw_bank#21]
Dear Support, Moodle 4.0.4+ (Build: 20221007) not working this plugin are you sure it is working with Moodle 4.0.4+ (Build: 20221007) not working?

**Comment by unesco-iesalc** [comment]
We are checking against 4.0.1. This week i'll test against 4.0.4.

What php version and database are using you?

Thanks.

**Comment by AbdullahAlSalim** [comment]
PHP 7.4
MySQL
moodle ver. Moodle 4.0.4+ (Build: 20221007)

**Comment by AbdullahAlSalim** [comment]
not showing when i want to add it to the course xxx.xxx/enrol/instances.php?id=#

**Comment by unesco-iesalc** [comment]
This plugin is not an enrollment plugin. It's a payment plugin. You must use in combination with the enroment plugin 'Enrolment on payment'.

This page   https://docs.moodle.org/400/en/Payment_gateways  https://docs.moodle.org/400/en/Enrolment_on_payment   , explains how to use the paypal and the payments enrolment plugin. Our plugin works almost the same.
