### ISSUE TITLE
Costs with decimals not allowed

### ISSUE THREAD

**Issue by izendegi** [unesco-iesalc/paygw_bank#24]
Hi there,

We are testing this plugin and got an error when a user tries to pay a course via this payment method:

> Debug: ERROR:  invalid input syntax for type bigint: "0.01"
> INSERT INTO mdl_paygw_bank (itemid,component,paymentarea,description,userid,totalamount,currency,code,usercheck,status,timecreated) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id
> Error code: dmlwriteexception
> * line 489 of /lib/dml/moodle_database.php: dml_write_exception thrown
> * line 293 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()
> * line 338 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->read_slave_query_end()
> * line 1091 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
> * line 1139 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->insert_record_raw()
> * line 204 of /payment/gateway/bank/classes/bank_helper.php: call to pgsql_native_moodle_database->insert_record()
> * line 90 of /payment/gateway/bank/pay.php: call to paygw_bank\bank_helper::create_bankentry()

It seems that the error comes from the cost having decimals (0.01) but the corresponding database field (totalamount) only allows integer values.

The field that defines that cost (mdl_enrol.cost) "allows decimals" (well, it's actually a varchar field), so it seems that the database field mdl_paygw_bank.totalamount should be changed to a type that allows them too.

**Comment by unesco-iesalc** [comment]
Yes.  This is a big mistake for me.  I expect to publish  a new versión fixing this this week.

**Comment by izendegi** [comment]
Thank you for your fast reply, @unesco-iesalc !

I've looked at the commit change and I think this line should also be changed for clean installations (TYPE="int" --> TYPE="char"), shouldn't it?

https://github.com/unesco-iesalc/paygw_bank/blob/main/db/install.xml#L16

**Comment by unesco-iesalc** [comment]
Yes. I thought the upgrade.php code was executed when installing it, but it is not.

**Comment by izendegi** [comment]
I've installed the new version and now works like a charm, thank you!
