### ISSUE TITLE
[Idea] To include in email which user requested bank payment

### ISSUE THREAD

**Issue by Buda9** [unesco-iesalc/paygw_bank#30]
Hi there and thank you very much for this great plugin.

I have an idea or suggestion for plugin improvement.

Currently admins can receive email saying: "There is a new bank payment request. code: {$a->code}". But we don't see student name in email. Would it be possible to include student name in such emails in one of the following versions?

Thank you!
- Davor

**Comment by unesco-iesalc** [comment]
It's a good idea. I'll try to create a new release in few days with this and another small improvements

**Comment by Buda9** [comment]
Thank you very much
