### ISSUE TITLE
enrol_wallet not compatible with paygw_bank

### ISSUE THREAD

**Issue by Buda9** [unesco-iesalc/paygw_bank#34]
Hi again,

I'm testing this great plugin with another plugin, [enrol_wallet](https://github.com/fmido88/moodle-enrol_wallet). However, it looks like it's not compatible.

Pages my_pending_pay.php and manage.php are throwing this error:

![Screenshot_2](https://github.com/unesco-iesalc/paygw_bank/assets/1422662/1e723378-7ffc-4fb9-8bc2-8444c87dc5dc)

Could you please take a quick look at screenshot and give me a hint where to look for the issue?

edit: from the error log

2024/04/19 12:42:57 [error] 495028#495028: *94718 FastCGI sent in stderr: "PHP message: Default exception handler: Zapisi podataka za tablicu enrol_wallet_items nisu pronađeni. Debug: SELECT * FROM {enrol_wallet_items} WHERE id = ?
[array (
  0 => 436,
)]
Error code: invalidrecord
* line 1658 of /lib/dml/moodle_database.php: dml_missing_record_exception thrown
* line 1634 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
* line 51 of /enrol/wallet/classes/payment/service_provider.php: call to moodle_database->get_record()
* line 8296 of /lib/moodlelib.php: call to enrol_wallet\payment\service_provider::get_payable()
* line 200 of /payment/classes/helper.php: call to component_class_callback()
* line 228 of /payment/classes/helper.php: call to core_payment\helper::get_payable()
* line 58 of /payment/gateway/bank/manage.php: call to core_payment\helper::get_gateway_configuration()" while reading upstream, client: 77.77.218.26, server: xyz.example.com, request: "GET /payment/gateway/bank/manage.php HTTP/2.0"

**Comment by unesco-iesalc** [comment]
Hi. I'm soon to release a new version, so i'll try to debug that and detect if is a bug of the payment plugin or the enrolment plugin(or both).

**Comment by Buda9** [comment]
You're my super hero. Thank you very much

**Comment by unesco-iesalc** [comment]
Hi. I just try the direct buy of the course, and add and amount to the wallet, and it works for me. 

Are you using the last version of both plugins?

**Comment by unesco-iesalc** [comment]
Hi. Do you still have this bug?

**Comment by Buda9** [comment]
@unesco-iesalc I tried to replicate error but I couldn't. So I deleted your plugin and reinstalled it, no issues so far. If it happens again I'll dig deeper into this issue. Thank you very much for your time and help
