### ISSUE TITLE
One bug - before you release v1.0.7

### ISSUE THREAD

**Issue by Buda9** [unesco-iesalc/paygw_bank#37]
Extra line [https://github.com/unesco-iesalc/paygw_bank/blob/51e57d6c7e88f7b83012f64e6e0121676a763b33/settings.php#L41](https://github.com/unesco-iesalc/paygw_bank/blob/51e57d6c7e88f7b83012f64e6e0121676a763b33/settings.php#L41)

**Comment by unesco-iesalc** [comment]
done
