### ISSUE TITLE
Database transaction started, but never commited.

### ISSUE THREAD

**Issue by ewallah** [unesco-iesalc/paygw_bank#38]
Your code uses database transactions 

But [line 50](https://github.com/unesco-iesalc/paygw_bank/blob/main/classes/bank_helper.php#L50) starts a transaction, but never commits, So line 54 is never committed, the hasfiles value never changes, and it is possible that other database queries never are committed because your transaction remains open...

In [line 112](https://github.com/unesco-iesalc/paygw_bank/blob/main/classes/bank_helper.php#L112) the commit is after the deliver order and the sending of the email(s). So the deliver order happens with non committed data.

In [line 163](https://github.com/unesco-iesalc/paygw_bank/blob/main/classes/bank_helper.php#L163) the commit is also very late.

If you do not catch exceptions that rollback the data, perhaps it is more interesting to get rid of transactions.

**Comment by unesco-iesalc** [comment]
Thanks a lot. I take ride of that
