### ISSUE TITLE
consider adding github actions support

### ISSUE THREAD

**Issue by danmarsden** [unesco-iesalc/paygw_bank#4]
Some of the tests run by the Moodle.org plugins db can be run via github actions on each commit in your github repo. Enabling this helps you to make sure future changes to your plugin will continue to follow the guidelines.

the short version - grab this file:
https://github.com/moodlehq/moodle-plugin-ci/blob/master/gha.dist.yml
rename it as ci.yml and put into the directory .github/workflows within tyour project eg:
https://github.com/danmarsden/moodle-mod_attendance/blob/MOODLE_311_STABLE/.github/workflows/ci.yml

then on every commit you make to github it will fire off a request to run the tests and will give you traffic lights beside each commit and generate a report.

**Comment by unesco-iesalc** [comment]
I just added the file. It's neccesary configure anything in the project?

**Comment by danmarsden** [comment]
nice work! - keep in mind that you aren't required to fix all the errors that it reports for plugins db approval - it's just something that would be nice to tidy up at some point.

**Comment by unesco-iesalc** [comment]
Thanks. I think i have the plugin ready to re-approval. The style and phpdoc errors doesn't bother me, it's just a little of boring work. I'll try to fix the error of grunt js compilation before the submit, because it's the only one that i don't have an explanation.

By the way, i tested the plugin in Moodle 4, and works!

**Comment by danmarsden** [comment]
cool! - I noticed a couple of other minor issues which I've just dropped into github - also - make sure you've added the language string for the new capability?  (you should be able to see this on the edit role page with debugging set to developer and display errors on.
